
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('comments').del()
    .then(function () {
      // Inserts seed entries
      return knex('comments').insert([
        {id: 1, user_id: 'isuh2gsef', post_id: 1, comment: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'},
        {id: 2, user_id: 'isuh2gsef', post_id: 2, comment: 'Curabitur accumsan arcu euismod tellus imperdiet finibus.'},
        {id: 3, user_id: 'isuh2gsef', post_id: 3, comment: 'Vestibulum facilisis diam eu ligula fermentum molestie.'},
        {id: 4, user_id: 'isuh2gsef', post_id: 4, comment: 'Cras et lectus at tellus imperdiet posuere.'},
        {id: 5, user_id: 'isuh2gsef', post_id: 5, comment: 'Ut egestas diam ut rutrum feugiat.'},
        {id: 6, user_id: 'isuh2gsef', post_id: 6, comment: 'Nulla porta risus sit amet tortor eleifend, id pharetra purus lacinia.'},
        {id: 7, user_id: 'vnsfh7sf', post_id: 7, comment: 'Proin dignissim nulla nec commodo suscipit.'},
        {id: 8, user_id: 'vnsfh7sf', post_id: 8, comment: 'Curabitur ut tellus tristique, fringilla ex at, suscipit magna.'},
        {id: 9, user_id: 'vnsfh7sf', post_id: 9, comment: 'Maecenas dignissim ante ac mi tristique ultricies.'},
        {id: 10, user_id: 'vnsfh7sf', post_id: 10, comment: 'Cras laoreet mi quis viverra tempus.'},
        {id: 11, user_id: 'vnsfh7sf', post_id: 11, comment: 'Nullam quis elit vitae sapien condimentum ullamcorper.'},
        {id: 12, user_id: 'vnsfh7sf', post_id: 12, comment: 'Fusce fermentum massa ac accumsan accumsan.'},
        {id: 13, user_id: 'su6hgsf', post_id: 13, comment: 'Fusce eu est at ligula lobortis lacinia sed id odio.'},
        {id: 14, user_id: 'su6hgsf', post_id: 14, comment: 'Vestibulum quis magna vitae arcu rutrum tincidunt.'},
        {id: 15, user_id: 'su6hgsf', post_id: 15, comment: 'Nam non mi mattis, viverra velit et, ultricies nunc.'},
        {id: 16, user_id: 'su6hgsf', post_id: 16, comment: 'Nullam pharetra diam at maximus euismod.'},
        {id: 17, user_id: 'su6hgsf', post_id: 17, comment: 'Nunc placerat metus at leo bibendum, nec rhoncus velit faucibus.'},
        {id: 18, user_id: 'su6hgsf', post_id: 18, comment: 'Vivamus dignissim mauris et auctor cursus.'},
        {id: 19, user_id: 'sefu2hsef', post_id: 19, comment: 'Sed viverra tellus ac pellentesque tincidunt.'},
        {id: 20, user_id: 'sefu2hsef', post_id: 20, comment: 'Vestibulum in risus sit amet nibh laoreet porttitor.'},
        {id: 21, user_id: 'sefu2hsef', post_id: 21, comment: 'Curabitur nec orci vel sapien tincidunt auctor sed id eros.'},
        {id: 22, user_id: 'sefu2hsef', post_id: 22, comment: 'Donec ac odio sed metus vestibulum dictum.'},
        {id: 23, user_id: 'sefu2hsef', post_id: 23, comment: 'Nam mattis mi non lacinia ullamcorper.'},
        {id: 24, user_id: 'sefu2hsef', post_id: 24, comment: 'Praesent eget odio et magna ullamcorper dignissim non porta leo.'},
        {id: 25, user_id: 'woie9yth', post_id: 25, comment: 'Donec pulvinar velit a tortor iaculis posuere.'},
        {id: 26, user_id: 'woie9yth', post_id: 26, comment: 'Suspendisse tincidunt arcu eu augue sagittis, a dictum nisi feugiat.'},
        {id: 27, user_id: 'woie9yth', post_id: 27, comment: 'Nullam mollis libero nec velit interdum sagittis.'},
        {id: 28, user_id: 'woie9yth', post_id: 28, comment: 'Sed gravida elit at vehicula hendrerit.'},
        {id: 29, user_id: 'woie9yth', post_id: 29, comment: 'Mauris faucibus nulla nec libero dictum, vel ultricies erat molestie.'},
        {id: 30, user_id: 'woie9yth', post_id: 30, comment: 'Fusce in tellus imperdiet, varius nisi tempus, dignissim magna.'},
        {id: 31, user_id: 'v2nsiduhwf', post_id: 1, comment: 'Aliquam lacinia velit non vulputate vulputate.'},
        {id: 32, user_id: 'v2nsiduhwf', post_id: 2, comment: 'Cras tempor ante in odio consectetur, ut eleifend dolor accumsan.'},
        {id: 33, user_id: 'v2nsiduhwf', post_id: 3, comment: 'Aenean et lacus ullamcorper tortor elementum dapibus.'},
        {id: 34, user_id: 'v2nsiduhwf', post_id: 4, comment: 'Proin laoreet ante vel auctor maximus.'},
        {id: 35, user_id: 'v2nsiduhwf', post_id: 5, comment: 'Praesent in erat elementum, feugiat erat a, mattis nibh.'},
        {id: 36, user_id: 'v2nsiduhwf', post_id: 6, comment: 'Pellentesque nec libero mattis, suscipit orci in, vulputate risus.'},
        {id: 37, user_id: 'woiesnf4dfn', post_id: 7, comment: 'Nam non neque lacinia, placerat felis cursus, molestie ante.'},
        {id: 38, user_id: 'woiesnf4dfn', post_id: 8, comment: 'Vivamus laoreet tellus at gravida varius.'},
        {id: 39, user_id: 'woiesnf4dfn', post_id: 9, comment: 'Nunc et lacus eu lorem venenatis consequat.'},
        {id: 40, user_id: 'woiesnf4dfn', post_id: 10, comment: 'Nullam porta nunc sagittis ante accumsan efficitur.'},
        {id: 41, user_id: 'woiesnf4dfn', post_id: 11, comment: 'Fusce in leo sit amet mi blandit ultricies.'},
        {id: 42, user_id: 'woiesnf4dfn', post_id: 12, comment: 'In et odio a mauris tempus eleifend tempus eget nisi.'},
        {id: 43, user_id: 'uvhsd5ifuh', post_id: 13, comment: 'Morbi sed velit aliquam, ultrices magna et, aliquam ipsum.'},
        {id: 44, user_id: 'uvhsd5ifuh', post_id: 14, comment: 'Integer tempus leo quis dolor pellentesque, sit amet sagittis tellus finibus.'},
        {id: 45, user_id: 'uvhsd5ifuh', post_id: 15, comment: 'Aliquam auctor massa ac risus congue pretium.'},
        {id: 46, user_id: 'uvhsd5ifuh', post_id: 16, comment: 'Suspendisse eget tortor sodales, commodo ex non, eleifend est.'},
        {id: 47, user_id: 'uvhsd5ifuh', post_id: 17, comment: 'Vivamus ornare ante in nisl vestibulum, lobortis ultricies augue imperdiet.'},
        {id: 48, user_id: 'uvhsd5ifuh', post_id: 18, comment: 'Morbi pretium ligula sed semper aliquam.'},
        {id: 49, user_id: 'njksvh2if', post_id: 19, comment: 'Praesent quis ipsum ac lorem tempus mattis.'},
        {id: 50, user_id: 'njksvh2if', post_id: 20, comment: 'Suspendisse suscipit diam a enim ultrices, nec pharetra urna euismod.'},
        {id: 51, user_id: 'njksvh2if', post_id: 21, comment: 'Curabitur eget nibh eget lorem tempus rhoncus.'},
        {id: 52, user_id: 'njksvh2if', post_id: 22, comment: 'Fusce ut urna ut ante placerat egestas.'},
        {id: 53, user_id: 'njksvh2if', post_id: 23, comment: 'Pellentesque ac lectus ut felis convallis fermentum nec ut nisi.'},
        {id: 54, user_id: 'njksvh2if', post_id: 24, comment: 'Quisque et diam feugiat sapien feugiat molestie.'},
        {id: 55, user_id: 'nlsdkfj09284', post_id: 25, comment: 'Sed consequat risus quis orci laoreet consectetur.'},
        {id: 56, user_id: 'nlsdkfj09284', post_id: 26, comment: 'Morbi at urna id magna vestibulum pulvinar.'},
        {id: 57, user_id: 'nlsdkfj09284', post_id: 27, comment: 'Fusce mattis mi eu sem pharetra imperdiet.'},
        {id: 58, user_id: 'nlsdkfj09284', post_id: 28, comment: 'Praesent gravida lacus sit amet tortor tempor rutrum.'},
        {id: 59, user_id: 'nlsdkfj09284', post_id: 29, comment: 'Vestibulum gravida turpis ac ex imperdiet convallis.'},
        {id: 60, user_id: 'nlsdkfj09284', post_id: 30, comment: 'Quisque sagittis justo id justo facilisis, in finibus nibh gravida.'},
        {id: 61, user_id: 'sefu2hsef', post_id: 8, comment: 'Curabitur a urna auctor, sodales purus vel, porttitor tellus.'},
        {id: 62, user_id: 'uvhsd5ifuh', post_id: 24, comment: 'Nam a lorem nec orci sodales elementum id ac ante.'},
        {id: 63, user_id: 'vnsfh7sf', post_id: 13, comment: 'Ut fringilla est in tellus finibus porttitor.'},
      ]);
    });
};
